### PR TITLE
Improve CLA workflow

### PR DESCRIPTION
**Pull request by C-nit**
actions to commit to other peoples forks was not something super easy to do, so I'm settling for a bit more verbosity and automation.

the issue will be closed with a comment to the commit that added the contributor. There is a notice to merge this into a PR.

Therefore there is no assignment of the issue any more.

Looks like this: https://github.com/C-nit/gt4sd-core/issues/9
and can also be triggered in a different way: https://github.com/C-nit/gt4sd-core/issues/11

### CODE REVIEW

**Comment by C-nit** [comment]
cla bot is only blocking because there are commits by the fictional 
```
          git config --local user.email "gt4sd-actions@github.com"
          git config --local user.name "GitHub Action"
```

**Comment by C-nit** [comment]
This one should really be a squash.

**Comment by drugilsberg** [comment]
> 

do you have any idea how to fix this? maybe adding fictional user to contributors? or set one of the repo maintainers as commiter?

**Review by drugilsberg — APPROVED** [review]
Looks great, see only the comment on the fictional user.

**Comment by C-nit** [comment]
> do you have any idea how to fix this? maybe adding fictional user to contributors? or set one of the repo maintainers as commiter?

I think it's a not an issue that will arise again. Here I was messing on the main on my fork to test the actions, and some of it's commits made it into the PR.

However in the usual flow Actions will commit to master. The merge commit of that in the PR is not a problem for the bot.

So I would just force the merge now. We have to revisit this only when we have GH Actions committing to PRs.

**Comment by C-nit** [comment]
@drugilsberg before I merge one thing that is hidden by the diff of the indentation:
I changed to use `secrets.GITHUB_TOKEN` that is an automatic ephemeral token set up per run.

I wanted to confirm there was no specific reason to use our own long lived token?

**Comment by drugilsberg** [comment]
> en by the diff of the indentation:
> I changed to use `secrets.GITHUB_TOKEN` that is an

totally ok with it, I wanted to operate the change anyhow, could you also use it in the Sphinx docs generation pipeline?

**Comment by C-nit** [comment]
Done, I also restricted permissions of the GITHUB_TOKEN with a bit of guessing what scopes are needed. Unfortunately the scopes itself are not well documented.

**Review by drugilsberg — APPROVED** [review]
LGTM, feel free to squash and merge

**Pull request merged**
