### PR TITLE
implementing model saving.

### PR DESCRIPTION
**Pull request by drugilsberg**
Initial definition of methods for configuration-training pipeline pairs.

Signed-off-by: Matteo Manica <drugilsberg@gmail.com>

### CODE REVIEW

**Comment by drugilsberg** [comment]
Initial attempt to handle model saving.

Here an example for algorithms compatible with the `paccmann-vae-trainer` pipeline:

```python
from gt4sd.training_pipelines.paccmann.core import PaccMannTrainingArguments
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# polymer blocks
#  gt4sd-trainer  --training_pipeline_name paccmann-vae-trainer --epochs 250 --batch_size 4 --n_layers 1 --rnn_cell_size 16 --latent_dim 16 --train_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --test_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --model_path /tmp/gt4sd-polymer-blocks/ --training_name testing --eval_interval 15 --save_interval 15 --no_selfies
from gt4sd.algorithms.generation.polymer_blocks.core import PolymerBlocksGenerator, PolymerBlocks
arguments = PaccMannTrainingArguments(model_path="/tmp/gt4sd-polymer-blocks/", training_name="testing")
PolymerBlocksGenerator.save_version_from_training_pipeline_arguments(arguments, "v1")
configuration = PolymerBlocksGenerator(algorithm_version="v1")
algorithm = PolymerBlocks(configuration=configuration)
print(list(algorithm.sample(5)))

# paccmann gp
# gt4sd-trainer  --training_pipeline_name paccmann-vae-trainer --epochs 250 --batch_size 4 --n_layers 1 --rnn_cell_size 16 --latent_dim 16 --train_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --test_smiles_filepath src/gt4sd/training_pipelines/tests/molecules.smi --model_path /tmp/gt4sd-paccmann-gp/ --training_name testing --eval_interval 15 --save_interval 15 --selfies
from gt4sd.algorithms.controlled_sampling.paccmann_gp.core import PaccMannGPGenerator, PaccMannGP
arguments = PaccMannTrainingArguments(model_path="/tmp/gt4sd-paccmann-gp/", training_name="testing")
PaccMannGPGenerator.save_version_from_training_pipeline_arguments(arguments, "v1")
configuration = PaccMannGPGenerator(algorithm_version="v1")
algorithm = PaccMannGP(configuration=configuration, target={"qed": {"weight": 1.0}, "sa": {"weight": 1.0}})
print(list(algorithm.sample(5)))

```

**Review by christofid — APPROVED** [review]
Looks great to me!

**Review by christofid — APPROVED** [review]
README looks good as well!

**Comment by drugilsberg** [comment]
> README looks good as well!

waiting for the CI to complete and will merge later.

**Pull request merged**
