### PR TITLE
Added toxicity and  affinity to visum notebook

### PR DESCRIPTION
**Pull request by edux300**
Signed-off-by: Eduardo <edux300@gmail.com>
Added toxicity (Tox21 model from https://github.com/PaccMann/paccmann_sarscov2) and affinity (Paccmann predictor) to the notebook.

@drugilsberg , I am not sure about one specific step in the notebook and I would really appreciate it if you could help:
When calling the sample in PaccMannGP for the first time the first line of the output is 

> configuring optimization for target: {'qed': {'weight': 1.0}, 'sa': {'weight': 1.0}}

However, on the second call to the same object (no reinitialization), in section "Sampling and Plotting Molecules with GT4SD", the first line reads:

> configuring optimization for target: {'qed': {}, 'sa': {}} 

Do you know if this has any influence on the molecules being generated?
I attached a PDF file with the output for convenience.

[visum-2022-handson-generative-models.pdf](https://github.com/GT4SD/gt4sd-core/files/9040779/visum-2022-handson-generative-models.pdf)

@helenaMontenegro , the notebook now requires users to download a small model, but I don't think this is a problem.

### CODE REVIEW

**Comment by drugilsberg** [comment]
> Signed-off-by: Eduardo [edux300@gmail.com](mailto:edux300@gmail.com) Added toxicity (Tox21 model from https://github.com/PaccMann/paccmann_sarscov2) and affinity (Paccmann predictor) to the notebook.
> 
> @drugilsberg , I am not sure about one specific step in the notebook and I would really appreciate it if you could help: When calling the sample in PaccMannGP for the first time the first line of the output is
> 
> > configuring optimization for target: {'qed': {'weight': 1.0}, 'sa': {'weight': 1.0}}
> 
> However, on the second call to the same object (no reinitialization), in section "Sampling and Plotting Molecules with GT4SD", the first line reads:
> 
> > configuring optimization for target: {'qed': {}, 'sa': {}}
> 
> Do you know if this has any influence on the molecules being generated? I attached a PDF file with the output for convenience.
> 
> [visum-2022-handson-generative-models.pdf](https://github.com/GT4SD/gt4sd-core/files/9040779/visum-2022-handson-generative-models.pdf)
> 
> @helenaMontenegro , the notebook now requires users to download a small model, but I don't think this is a problem.

will check tomorrow first thing, thanks for the contribution.

**Comment by drugilsberg** [comment]
> Signed-off-by: Eduardo [edux300@gmail.com](mailto:edux300@gmail.com) Added toxicity (Tox21 model from https://github.com/PaccMann/paccmann_sarscov2) and affinity (Paccmann predictor) to the notebook.
> 
> @drugilsberg , I am not sure about one specific step in the notebook and I would really appreciate it if you could help: When calling the sample in PaccMannGP for the first time the first line of the output is
> 
> > configuring optimization for target: {'qed': {'weight': 1.0}, 'sa': {'weight': 1.0}}
> 
> However, on the second call to the same object (no reinitialization), in section "Sampling and Plotting Molecules with GT4SD", the first line reads:
> 
> > configuring optimization for target: {'qed': {}, 'sa': {}}
> 
> Do you know if this has any influence on the molecules being generated? I attached a PDF file with the output for convenience.
> 
> [visum-2022-handson-generative-models.pdf](https://github.com/GT4SD/gt4sd-core/files/9040779/visum-2022-handson-generative-models.pdf)
> 
> @helenaMontenegro , the notebook now requires users to download a small model, but I don't think this is a problem.

Hey @edux300 that is a great catch, I double checked the logic and this indeed was a bug in handling the target in `PaccMannGP`. Luckily in this and the other examples this was not an issue since the weights passed were equal and, ig ignored, they default to the same value (e.g., passing 1.0 in both).
I'm preparing a PR that should address the issue correctly. I will ping you to rerun a test in the notebook to acknowledge the fix.

Regarding the data download, I think there is no issue, but I let you and @helenaMontenegro decide on this.

**Review by drugilsberg — COMMENTED** [review]
The notebook changes look good, pending the fix implemented here: https://github.com/GT4SD/gt4sd-core/pull/108.

**Comment by drugilsberg** [comment]
> PR addressing the issue merged, on my side is good to go. Maybe rerun the notebook and verify that now the target is appropriately preserved in the second call.

@helenaMontenegro @edux300 waiting for your green light to merge.

**Comment by edux300** [comment]
Hey, this new commit corrects a small bug in one of the sections of the notebook.
Regarding PaccMannGP, when I run the notebook this time the issue was addressed (pdf with output attached).

[visum-2022-handson-generative-models.pdf](https://github.com/GT4SD/gt4sd-core/files/9049508/visum-2022-handson-generative-models.pdf)


Ready to merge on our end.
Thank you for reviewing this!

**Comment by drugilsberg** [comment]
> Hey, this new commit corrects a small bug in one of the sections of the notebook. Regarding PaccMannGP, when I run the notebook this time the issue was addressed (pdf with output attached).
> 
> [visum-2022-handson-generative-models.pdf](https://github.com/GT4SD/gt4sd-core/files/9049508/visum-2022-handson-generative-models.pdf)
> 
> Ready to merge on our end. Thank you for reviewing this!

Thanks to both of you for the nice work 🚀

**Pull request merged**
