### PR TITLE
fix: update requirements to set up CLI commands

### PR DESCRIPTION
**Pull request by jannisborn**
Solves to #92 which was closed even though those changes were never fixed on `main`.

Effectively in the dev setup thus far, the CLI commands were not functional since `wheel` and `protobuf` were complaining

### CODE REVIEW

**Review by drugilsberg — APPROVED** [review]
It looks good to me, I thought the issue was closed because the problem was not relevant anymore.

**Comment by jannisborn** [comment]
I also took the opportunity to sort all requirements we have alphabetically. For the future we should add new requirements in the correct line

**Comment by jannisborn** [comment]
I also added an example (to be expanded) under `examples/CLI/README.md` which lists all the available algorithms for inference.
I think it can help to get started and get an overview of all inference algorithms that are there

**Comment by jannisborn** [comment]
Closes #92

**Review by drugilsberg — APPROVED** [review]
Amazing work

**Pull request merged**
