### PR TITLE
fix main

### PR DESCRIPTION
**Pull request by georgosgeorgos**

### CODE REVIEW

**Comment by georgosgeorgos** [comment]
One issue is that the library is not compatible with the last `pytorch==1.13.0`. Until last week the stable version was `1.12.1`. Now we install the 1.12.1 using `conda install -c pytorch pytorch` but then the cpu/gpu_requirements.txt uninstalls and upgrades torch to 1.13.0 using pypi.

```
Attempting uninstall: torch
Found existing installation: torch 1.12.1
Uninstalling torch-1.12.1:
Successfully uninstalled torch-1.12.1
```

and running conda list | grep torch

```
pytorch-lightning         1.8.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.0.9           py38_torch_1.12.0_cu116    pyg
torch                     1.13.0                   pypi_0    pypi
torch-cluster             1.6.0                    pypi_0    pypi
torch-geometric           2.1.0.post1              pypi_0    pypi
torch-sparse              0.6.15                   pypi_0    pypi
torchdrug                 0.2.0.post1              pypi_0    pypi
torchmetrics              0.10.2                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
```

**Comment by drugilsberg** [comment]
> One issue is that the library is not compatible with the last `pytorch==1.13.0`. Until last week the stable version was `1.12.1`. Now we install the 1.12.1 using `conda install -c pytorch pytorch` but then the cpu/gpu_requirements.txt uninstalls and upgrades torch to 1.13.0 using pypi.
> 
> ```
> Attempting uninstall: torch
> Found existing installation: torch 1.12.1
> Uninstalling torch-1.12.1:
> Successfully uninstalled torch-1.12.1
> ```
> 
> and running `conda list | grep torch` in the conda env:
> 
> ```
> pytorch-lightning         1.8.0                    pypi_0    pypi
> pytorch-mutex             1.0                        cuda    pytorch
> pytorch-scatter           2.0.9           py38_torch_1.12.0_cu116    pyg
> torch                     1.13.0                   pypi_0    pypi
> torch-cluster             1.6.0                    pypi_0    pypi
> torch-geometric           2.1.0.post1              pypi_0    pypi
> torch-sparse              0.6.15                   pypi_0    pypi
> torchdrug                 0.2.0.post1              pypi_0    pypi
> torchmetrics              0.10.2                   pypi_0    pypi
> torchvision               0.14.0                   pypi_0    pypi
> ```
> 
> We never had this issue because conda and pypi were both referring to the same stable version 1.12.1.

🙈 
```
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 11.6. Please reinstall the torch_scatter that matches your PyTorch install
```

**Comment by georgosgeorgos** [comment]
> RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 11.6. Please reinstall the torch_scatter that matches your PyTorch install
> ```

How did you obtain this error? I cannot replicate it.

**Review by drugilsberg — APPROVED** [review]
Looks good, great job

**Pull request merged**
