### PR TITLE
feat: setting up binder hosting.

### PR DESCRIPTION
**Pull request by drugilsberg**
Setting up Binder, waiting for the availability of a docker image.

### CODE REVIEW

**Comment by jannisborn** [comment]
Nice, the binder setup runs smoothly. Unfortunately the kernel died when running all models together. 
I added an extra line to the dockerfile to install the notebook requirements

**Comment by drugilsberg** [comment]
@jannisborn PR ready for review, everything seems to work fine, apart from the known resources limitations coming from mybinder.

**Review by jannisborn — APPROVED** [review]
Very nice! Last thought: we're not installing the `vcs_requirements` inside the container, so I assume that the gt4sd base image ensures that **all** of them are installed with correct versions. I selectively verified that the algorithms can be executed in the binder and for all the ones I tested it was working

**Comment by drugilsberg** [comment]
> Very nice! Last thought: we're not installing the `vcs_requirements` inside the container, so I assume that the gt4sd base image ensures that **all** of them are installed with correct versions. I selectively verified that the algorithms can be executed in the binder and for all the ones I tested it was working

I believe we do, we use the conda.yml that it's ensuring they are installed :)

**Pull request merged**
